### ISSUE TITLE
"utils.hpp" is missing

### ISSUE THREAD

**Issue by mensong** [githubyang/SparrowJS#1]
"utils.hpp" is missing, forget commit?

**Comment by warjiang** [comment]
> "utils.hpp" is missing, forget commit?

SparrowJS 实际上抄了一遍https://github.com/gfwilliams/tiny-js ，这个项目是用Makefile构建的，如果有兴趣，可以参考我用CMake修改过后的https://github.com/warjiang/tiny-js，配合CLion，轻松调试
